source: /Users/mj12albert/Servers/ipgpay.com/source
destination: /Users/mj12albert/Servers/ipgpay.com/build
timezone: Asia/Hong_Kong
encoding: utf-8
include: [
  '*.scss',
  '*.css.map'
]
exclude: [
  'Gemfile*'
]